### ISSUE TITLE
Issue with Part 2 on MacOS Maui RC3, VS 2022 RC2 (Cannot refresh monkey list)

### ISSUE THREAD

**Issue by polygonsheep** [dotnet-presentations/dotnet-maui-workshop#49]
MacOS building for Mac and iphone simulator. 
MAUI RC3
VS for Mac 2022 RC2
Monterey 12.3.1
Intel mac mini 
iphone Simulator 13.3.1 (977.2)

Completed Part 2, hit the "Get Monkeys" button and the list pulls from internet and propagates view correctly.  Hitting "Get Monkeys" a second time, not good.

 - On Mac desktop build, the list clears and repopulates with just the first monkey (Baboon). White space below still allows scrolling but no other monkeys showing.

- On iphone simulator, throws exception.

Reason: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
   at System.Collections.Generic.List`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].System.Collections.IList.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewDelegator`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.ReorderableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
   at UIKit.UICollectionView.InsertItems(NSIndexPath[] indexPaths)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass41_0.<Add>b__0()
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Update(Action update, NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass37_0.<CollectionChanged>b__0()
   at Foundation.NSAsyncActionDispatcher.Apply()

**Comment by jamesmontemagno** [comment]
Are you sure you are on the latest RC 3? I am not experiencing this anymore as it was fixed there.

**Comment by polygonsheep** [comment]
Hi James, it's possible. I followed the instructions here https://github.com/dotnet/maui/wiki/macOS-Install.  Is there a command line to check the maui version installed?

**Comment by polygonsheep** [comment]
Removed the .net sdk and started over. Definitely installed rc3 this time, but now I have other issues and can't get back to even test this. 

I will assume I did not have RC3 properly installed and close this. Sorry for the confusion.

**Comment by jamesmontemagno** [comment]
no worries! it will soon ship with VS for mac so should be easy peasy

**Comment by polygonsheep** [comment]
Hey James,

I am confident I do have RC3 properly installed now and I'm still seeing this Out of Range Exception when clicking "Get Monkeys" a second time.  Thanks.

**Comment by polygonsheep** [comment]
Fixed with GA release
